### ISSUE TITLE
Matchers for json fields

### ISSUE THREAD

**Issue by g4s8** [g4s8/matchers-json#1]
Add matchers for json objects and values

**Comment by g4s8** [comment]
@rultor hello

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#2](https://github.com/g4s8/matchers-json/issues/2) is still not solved.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#7](https://github.com/g4s8/matchers-json/issues/7) is still not solved; solved: [#2](https://github.com/g4s8/matchers-json/issues/2).
