### ISSUE TITLE
Matcher to check whether json contains certain field without value check

### ISSUE THREAD

**Issue by olenagerasimova** [g4s8/matchers-json#6]
It would be nice to have opportunity to check whether json contains certain field without exact field value check, for example json contains field 
- with the any value of given type
- with any non-empty string value 
- with string value that starts/ends/contains given sub string

**Comment by g4s8** [comment]
@olenagerasimova you can use `JsonValueIs` primary constructor with any matcher:
```java
MatcherAssert.assertThat(
    Json.createValue("Starting with 1 2 3"),
    new JsonValueIs(
        JsonValue.ValueType.STRING,
        Matchers.startsWith("Starting")
    )
);
```
see https://github.com/g4s8/matchers-json/commit/34f5de59f409a83aae2b17ca1d8c20197a1257c3

**Comment by g4s8** [comment]
@rultor release, tag=`0.3.1`
